name: Send Message on Pull Request open.

on:
  pull_request:
    types: [opened, reopened]

jobs:
  sendMessage:
    runs-on: ubuntu-latest

    steps:
      - uses: hmarr/debug-action@v2
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          debug: true
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.event.pull_request.html_url }}
